# Generated by Django 2.2.3 on 2019-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_result',
            name='heart',
        ),
        migrations.AddField(
            model_name='search_result',
            name='netflix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='watcha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='youtube',
            field=models.BooleanField(default=False),
        ),
    ]
