# Generated by Django 2.2 on 2019-08-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190731_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_result',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='search_result',
            name='action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='animation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='comedy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='drama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='fantasy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='horror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='romance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='sf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='search_result',
            name='thriller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='search_result',
            name='poster',
            field=models.TextField(blank=True),
        ),
    ]
