# Generated by Django 2.2 on 2019-08-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190802_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search_result',
            new_name='Movie',
        ),
    ]
