# Generated by Django 2.2.3 on 2019-08-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190803_1515'),
        ('main', '0005_auto_20190803_0303'),
    ]

    operations = [
    ]
