# Generated by Django 2.2 on 2019-08-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20190803_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='youtube',
        ),
    ]
