# Generated by Django 2.2.1 on 2019-08-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190804_0154'),
        ('main', '0005_auto_20190802_1916'),
    ]

    operations = [
    ]
