# Generated by Django 2.2 on 2019-08-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20190805_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='opening',
            field=models.CharField(default='1990', max_length=100),
        ),
    ]
